# Generated by Django 4.2.4 on 2023-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('mission', models.CharField(max_length=200)),
                ('date_debut', models.CharField(max_length=200)),
                ('competences', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
            ],
        ),
    ]
