# Generated by Django 4.2.4 on 2023-08-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='extrator.processextraction'),
            preserve_default=False,
        ),
    ]
