# Generated by Django 4.2.4 on 2023-08-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0003_processextraction_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='processextraction',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
    ]
